version: 2
jobs:
  build:
    working_directory: /tmp/mafuyu-web
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - restore_cache:
          key: mafuyu-web-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build app
          command: yarn build
      - save_cache:
          key: mafuyu-web-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - /tmp/mafuyu-web/node_modules
            - /tmp/mafuyu-web/.cache/yarn
      - run:
          name: Deploy to Firebase hosting
          command: ./node_modules/.bin/firebase deploy --project $FIREBASE_PROJECT_ID --token=$FIREBASE_DEPLOY_TOKEN